# Naukri Credentials (Update with your actual credentials)
naukri.username=mehvishshaikh1112@gmail.com
naukri.password=Smehvi@7797
# Naukri Credentials (Will be set via environment variables in CI/CD)
#naukri.username=${NAUKRI_USERNAME}
#naukri.password=${NAUKRI_PASSWORD}

# Naukri URL
naukri.url=https://www.naukri.com

# Browser Settings
browser.headless=${BROWSER_HEADLESS:true}
browser.type=chrome  # Changed from chromium to chrome
browser.timeout=60000